DROP TABLE IF EXISTS `tvt`;
CREATE TABLE `tvt` (
  `eventName` VARCHAR(255) NOT NULL DEFAULT '',
  `eventDesc` VARCHAR(255) NOT NULL DEFAULT '',
  `joiningLocation` VARCHAR(255) NOT NULL DEFAULT '',
  `minlvl` INT(4) NOT NULL DEFAULT 0,
  `maxlvl` INT(4) NOT NULL DEFAULT 0,
  `npcId` INT(8) NOT NULL DEFAULT 0,
  `npcX` INT(11) NOT NULL DEFAULT 0,
  `npcY` INT(11) NOT NULL DEFAULT 0,
  `npcZ` INT(11) NOT NULL DEFAULT 0,
  `npcHeading` INT(11) NOT NULL DEFAULT 0,
  `rewardId` INT(11) NOT NULL DEFAULT 0,
  `rewardAmount` INT(11) NOT NULL DEFAULT 0,
  `teamsCount` INT(4) NOT NULL DEFAULT 0,
  `joinTime` INT(11) NOT NULL DEFAULT 0,
  `eventTime` INT(11) NOT NULL DEFAULT 0,
  `minPlayers` INT(4) NOT NULL DEFAULT 0,
  `maxPlayers` INT(4) NOT NULL DEFAULT 0
) DEFAULT CHARSET=utf8;