ALTER TABLE `character_hennas`
  MODIFY `charId` INT UNSIGNED NOT NULL,
  MODIFY `symbol_id` TINYINT UNSIGNED NOT NULL,
  MODIFY `slot` TINYINT UNSIGNED NOT NULL,
  MODIFY `class_index` TINYINT UNSIGNED NOT NULL;

ALTER TABLE `character_shortcuts`
  MODIFY `charId` INT UNSIGNED NOT NULL,
  MODIFY `slot` TINYINT NOT NULL,
  MODIFY `page` TINYINT NOT NULL,
  MODIFY `type` TINYINT NOT NULL,
  MODIFY `shortcut_id` INT NOT NULL,
  MODIFY `level` SMALLINT(3) NOT NULL,
  MODIFY `class_index` TINYINT UNSIGNED NOT NULL;

ALTER TABLE `character_skills`
  MODIFY `charId` INT UNSIGNED NOT NULL,
  MODIFY `skill_id` SMALLINT UNSIGNED NOT NULL,
  MODIFY `skill_level` SMALLINT(3) NOT NULL,
  MODIFY `skill_name` VARCHAR(40),
  MODIFY `class_index` TINYINT UNSIGNED NOT NULL;

ALTER TABLE `character_skills_save`
  MODIFY `charId` INT UNSIGNED NOT NULL,
  MODIFY `skill_id` SMALLINT UNSIGNED NOT NULL,
  MODIFY `skill_level` SMALLINT(3) NOT NULL,
  MODIFY `effect_count` INT NOT NULL,
  MODIFY `effect_cur_time` INT NOT NULL,
  MODIFY `reuse_delay` INT NOT NULL,
  MODIFY `systime` BIGINT UNSIGNED NOT NULL,
  MODIFY `restore_type` TINYINT(1) UNSIGNED NOT NULL,
  MODIFY `class_index` TINYINT UNSIGNED NOT NULL,
  MODIFY `buff_index` SMALLINT UNSIGNED NOT NULL;

ALTER TABLE `character_subclasses`
  MODIFY `charId` INT UNSIGNED NOT NULL,
  MODIFY `class_id` TINYINT UNSIGNED NOT NULL,
  MODIFY `exp` BIGINT UNSIGNED NOT NULL,
  MODIFY `sp` INT UNSIGNED NOT NULL,
  MODIFY `level` TINYINT(2) UNSIGNED NOT NULL,
  MODIFY `class_index` TINYINT UNSIGNED NOT NULL;
