@echo off
title ------------------------------------ = Dark-Moon Dev Team Database Installer = ------------------------------------
color 02
REM This is Dark-Moon Database Inastaller.
REM ############################################
REM ## You can change here your own DB params ##
REM ############################################
REM MYSQL BIN PATH
REM Default values: 
set mysqlBinPath=C:\Program Files\MySQL\MySQL Server 4.1\bin\

REM #########################################
REM ##for mysql server users on x64 systems #
REM #########################################
REM C:\Program Files (x86)\MySQL\MySQL Server 5.0\bin

REM ###########################################
REM ##for mysql server users on Win XP system #
REM ###########################################
REM C:\Program Files\MySQL\MySQL Server 5.0\bin
REM C:\Program Files\MySQL\MySQL Server 5.0\bin

REM LOGINSERVER
set lsuser=root
set lspass=
set lsdb=Dark-Moon
set lshost=localhost

REM GAMESERVER
set gsuser=root
set gspass=
set gsdb=Dark-Moon
set gshost=localhost
REM ############################################

set mysqldumpPath="%mysqlBinPath%\mysqldump"  
set mysqlPath="%mysqlBinPath%\mysql"  

echo.
echo  ______________________________________________________________________
echo !                                                                      !
echo !                               Welcome to                             !
echo !           ** Dark-Moon Dev Team  Database Installer **         !
echo !                           ** [LoginServer] **                        !
echo !           ATTENTION! FULL INSTALL DESTROY ALL EXISTING ACCOUNTS!     !
echo !______________________________________________________________________!
echo. 
echo.
echo.
echo.
echo LOADING...
echo.
%mysqldumpPath% --add-drop-table -h %lshost% -u %lsuser% --password=%lspass% %lsdb% > loginserver_backup.sql
echo PLEASE SELECT YOUR INSTALL TYPE :
echo.
echo WARNING: FULL INSTALL (F) FOR A COMPLETE LOGINSERVER INSTALL.
echo.         
echo          SKIP (S) TO SKIP LOGINSERVER DATABASE INSTALL.          
echo.
echo          QUIT (Q) TO EXIT THIS PROGRAM.  
echo.
:asklogin
set loginprompt=x
set /p loginprompt=WHAT'S YOUR CHOICE ? 
echo.
if /i %loginprompt%==F goto logininstall
if /i %loginprompt%==S goto gsinst
if /i %loginprompt%==Q goto end
goto asklogin

:logininstall
echo OPERATION IN PROGRESS...
echo PREPARATION TO INSTALL...
%mysqlPath% -h %lshost% -u %lsuser% --password=%lspass% -D %lsdb% < login_install.sql
echo.

echo PREPARATION DONE...
echo INSTALLING TABLES...
echo ACCOUNTS                                    PROCESSING...
%mysqlPath% -h %lshost% -u %lsuser% --password=%lspass% -D %lsdb% < ../sql/accounts.sql
echo GAMESERVERS                                 PROCESSING...
%mysqlPath% -h %lshost% -u %lsuser% --password=%lspass% -D %lsdb% < ../sql/gameservers.sql
echo.
echo LOGINSERVER DATABASE INSTALL COMPLETED !
echo.
echo.
echo.
:gsinst
CLS
echo.
echo  ______________________________________________________________________
echo  !                                                                     !
echo  !               ** Dark-Moon Dev Team Database Installer **     !     
echo  !                             ** [Gameserver] **                      ! 
echo  !          ATTENTION! FULL INSTALL DESTROY ALL EXISTING CHARACTERS!   !
echo  !_____________________________________________________________________!
echo.
echo LOADING...
:gsbackup
%mysqldumpPath% --add-drop-table -h %gshost% -u %gsuser% --password=%gspass% %gsdb% > gameserver_backup.sql
echo.
echo.
echo PLEASE SELECT YOUR INSTALL TYPE :
echo.
echo WARNING: FULL INSTALL (F) FOR A COMPLETE GAMESERVER INSTALL.
echo.           
echo          UPGRADE INSTALL (U) FOR A GAMESERVER UPGRADE INSTALL.
echo.         
echo          SKIP (S) TO SKIP GAMESERVER DATABASE INSTALL. 
echo.
echo          QUIT (Q) TO EXIT THIS PROGRAM.          
echo.     
:asktype
set installtype=x
set /p installtype=WHAT'S YOUR CHOICE ?
echo.
echo.
if /i %installtype%==F goto fullinstall
if /i %installtype%==U goto upgradeinstall
if /i %installtype%==S goto additional_features_setup
if /i %installtype%==Q goto end
goto asktype

:fullinstall
echo OPERATION IN PROGRESS...
echo PREPARATION TO INSTALL...
echo.
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < gs_install.sql
echo.
echo PREPARATION DONE...
echo INSTALLING TABLES...
echo.
echo.
echo ACCOUNT DATA                                PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/account_data.sql
echo ARMOR                                       PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/armor.sql
echo ARMOR SETS                                  PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/armorsets.sql
echo AUCTION                                     PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/auction.sql
echo AUCTION BID                                 PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/auction_bid.sql
echo AUCTION WATCH                               PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/auction_watch.sql
echo AUGMENTATIONS                               PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/augmentations.sql
echo AUTO ANNOUNCEMENTS                          PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/auto_announcements.sql
echo AUTO CHAT                                   PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/auto_chat.sql
echo AUTO CHAT TEXT                              PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/auto_chat_text.sql
echo BOXACESS                                    PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/boxaccess.sql
echo BOXES                                       PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/boxes.sql
echo BUFF TEMPLATES                              PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/buff_templates.sql
echo CASTLE                                      PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/castle.sql
echo CASTLE DOOR                                 PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/castle_door.sql
echo CASTLE DOOR UPGRADE                         PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/castle_doorupgrade.sql
echo CASTLE MANOR PROCURE                        PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/castle_manor_procure.sql
echo CASTLE MANOR PRODUCTION                     PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/castle_manor_production.sql
echo CASTLE SIEGE GUARDS                         PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/castle_siege_guards.sql
echo CHARACTER TEMPLATES                         PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/char_templates.sql
echo CHARACTER FRIENDS                           PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/character_friends.sql
echo CHARACTER HENNA                             PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/character_hennas.sql
echo CHARACTER MACRO                             PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/character_macroses.sql
echo CHARACTER OLYMPIADS                         PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/character_olympiad.sql
echo CHARACTER QUEST                             PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/character_quests.sql
echo CHARACTER RAID POINTS                       PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/character_raidpoints.sql
echo CHARACTER RECIPEBOOK                        PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/character_recipebook.sql
echo CHARACTER RECOMMENDS                        PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/character_recommends.sql
echo CHARACTER SHORTCUT                          PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/character_shortcuts.sql
echo CHARACTER SKILL                             PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/character_skills.sql
echo CHARACTER SKILL SAVE                        PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/character_skills_save.sql
echo CHARACTER STATS                             PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/character_stats.sql
echo CHARACTER SUBCLASS                          PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/character_subclasses.sql
echo CHARACTER                                   PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/characters.sql
echo CLAN DATA                                   PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/clan_data.sql
echo CLAN HALL                                   PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/clanhall.sql
echo CLAN PRIVILEGIES BY RANK                    PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/clan_privs.sql
echo CLAN SKILLS                                 PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/clan_skills.sql
echo CLAN SUB PRIVILEGIES                        PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/clan_subpledges.sql
echo CLAN WAR                                    PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/clan_wars.sql
echo CLAN HALL FUNCTIONS                         PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/clanhall_functions.sql
echo CLASS LIST                                  PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/class_list.sql
echo COUPLES                                     PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/couples.sql
echo CURSED WEAPONS                              PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/cursed_weapons.sql
echo DROPLIST                                    PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/droplist.sql
echo ENCHANT SKILL TREES                         PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/enchant_skill_trees.sql
echo ETC ITEM                                    PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/etcitem.sql
echo FACTION QUESTS                              PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/faction_quests.sql
echo FISH                                        PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/fish.sql
echo FISHING SKILL TREE                          PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/fishing_skill_trees.sql
echo FORTRESS SIEGE                              PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/fortress_siege.sql
echo FORUMS                                      PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/forums.sql
echo FOUR SEPULCHURS SPAWNLIST                   PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/four_sepulchers_spawnlist.sql
echo GAMES                                       PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/games.sql
echo GLOBAL TASKS                                PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/global_tasks.sql
echo GM AUDIT                                    PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/gm_audit.sql
echo HENNA                                       PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/henna.sql
echo HENNA TREES                                 PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/henna_trees.sql
echo HEROES                                      PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/heroes.sql
echo ITEM                                        PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/items.sql
echo ITEMS ON GROUND                             PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/itemsonground.sql
echo LOCATION                                    PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/locations.sql
echo LVL UP GAIN                                 PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/lvlupgain.sql
echo MERCHANT AREAS LIST                         PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/merchant_areas_list.sql
echo MERCHANT BUYLISTS                           PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/merchant_buylists.sql
echo MERCHANT SHOP IDS                           PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/merchant_shopids.sql
echo MERCHANT                                    PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/merchants.sql
echo MINIONS                                     PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/minions.sql
echo NPC                                         PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/npc.sql
echo NPC SKILLS                                  PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/npcskills.sql
echo OLYMPIAD NOBLES                             PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/olympiad_nobles.sql
echo PETITION                                    PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/petitions.sql
echo PET                                         PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/pets.sql
echo PET STATS                                   PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/pets_stats.sql
echo PLEDGE SKILL TREES                          PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/pledge_skill_trees.sql
echo POST                                        PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/posts.sql
echo QUEST GLOBAL DATA                           PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/quest_global_data.sql
echo RAID BOSS SPAWNLIST                         PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/raidboss_spawnlist.sql
echo RANDOM SPAWN                                PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/random_spawn.sql
echo RANDOM SPAWN LOC                            PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/random_spawn_loc.sql
echo RECORD                                      PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/record.sql
echo SEVEN SIGNS                                 PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/seven_signs.sql
echo SEVEN SIGNS FESTIVAL                        PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/seven_signs_festival.sql
echo SEVEN SIGNS STATUS                          PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/seven_signs_status.sql
echo SIEGE CLANS                                 PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/siege_clans.sql
echo SKILL LEARN                                 PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/skill_learn.sql
echo SKILL SPEELBOOKS                            PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/skill_spellbooks.sql
echo SKILL TREE                                  PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/skill_trees.sql
echo SPAWNLIST                                   PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/spawnlist.sql
echo TELEPORT                                    PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/teleport.sql
echo TOPIC                                       PROCESSING... 
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/topic.sql
echo VERSION                                     PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/version.sql  
echo WALKER ROUTES                               PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/walker_routes.sql
echo WEAPON                                      PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/weapon.sql
echo CTF                                         PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/ctf.sql
echo CTF TEAMS                                   PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/ctf_teams.sql
echo DEATH MATCH EVENT                           PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/dm.sql
echo TVT                                         PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/tvt.sql
echo TVT TEAMS                                   PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/tvt_teams.sql
echo VIP EVENT                                   PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/vipinfo.sql
echo RAID EVENTS SPAWNLIST                       PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/raid_event_spawnlist.sql
echo RAID PRIZES                                 PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/raid_prizes.sql
echo JAIL SPAWNLIST                              PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/jail_spawnlist.sql
echo CUSTOM ARMOR                                PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/custom_armor.sql
echo CUSTOM ETCITEM                              PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/custom_etcitem.sql
echo CUSTOM MERCHANT BUYLISTS                    PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/custom_merchant_buylists.sql
echo CUSTOM MERCHANT SHOP IDS                    PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/custom_merchant_shopids.sql
echo CUSTOM NPC                                  PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/custom_npc.sql
echo CUSTOM SPAWNLIST                            PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/custom_spawnlist.sql
echo CUSTOM TELEPORTS                            PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/custom_teleports.sql
echo CUSTOM WEAPON                               PROCESSING...
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/custom_weapon.sql
echo FOUR SEPULCHERS SPAWNLISTS                  PROCESSING...      
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/four_sepulchers_spawnlist.sql
echo VANHALTER SPAWNLIST                         PROCESSING...     
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/vanhalter_spawnlist.sql
echo GRANDBOSS INTERVAL LIST                     PROCESSING...   
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/grandboss_intervallist.sql
echo BENOM DATA                                  PROCESSING...   
%mysqlPath% -h %gshost% -u %gsuser% --password=%gspass% -D %gsdb% < ../sql/benomdata.sql
goto end
:upgradeinstall
:asktwo
CLS
echo PRESS (Y) FOR UPDATE
echo PRESS (N) FOR RETURN
echo PRESS (Q) FOR QUIT 
set upgrconfirm=x
set /p upgrconfirm=WHAT'S YOUR CHOICE ?
echo.
echo.
if /i %upgrconfirm%==Y goto upgradebegin
if /i %upgrconfirm%==N goto gsinst
if /i %upgrconfirm%==Q goto end
goto asktwo
:upgradebegin
echo        !!! Please configure DMUpdater.bat before continue !!!
echo                !!! Press any key for begin update !!!
pause
DMUpdater.bat
:end
echo DATABASE INSTALL COMPLETED !
echo.
echo.
echo.
echo.
echo  ______________________________________________________________________
echo !          Developed by Dark-Moon Development Team.                   !
echo !          COPYRIGHT 2008 - 2009 - ALL RIGHTS RESERVED.               !
echo !_____________________________________________________________________!
echo.
echo.
echo.
pause