CREATE TABLE IF NOT EXISTS `character_effects` (
  `charId` INT UNSIGNED NOT NULL,
  `classIndex` TINYINT UNSIGNED NOT NULL,
  `buffIndex` SMALLINT UNSIGNED NOT NULL,
  `skillId` SMALLINT UNSIGNED NOT NULL,
  `skillLvl` SMALLINT UNSIGNED NOT NULL,
  `count` INT UNSIGNED NOT NULL,
  `remaining` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`charId`,`classIndex`,`buffIndex`)
) DEFAULT CHARSET=utf8;
