ALTER TABLE npc ADD COLUMN ss int(4) DEFAULT 0;
ALTER TABLE npc ADD COLUMN bss int(4) DEFAULT 0;
ALTER TABLE npc ADD COLUMN ss_rate int(3) DEFAULT 0;
ALTER TABLE npc ADD COLUMN AI varchar(8) DEFAULT "fighter";