ALTER TABLE `auction_bid`
  MODIFY `bidderName` VARCHAR(35) NOT NULL,
  MODIFY `clan_name` VARCHAR(45) NOT NULL,
  MODIFY `maxBid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `time_bid` BIGINT NOT NULL DEFAULT 0;

ALTER TABLE `auction`
  MODIFY `id` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `sellerId` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `sellerName` VARCHAR(35) NOT NULL DEFAULT "NPC",
  MODIFY `sellerClanName` VARCHAR(45) NOT NULL DEFAULT "",
  MODIFY `itemId` SMALLINT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `itemObjectId` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `itemQuantity` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `startingBid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `currentBid` INT UNSIGNED NOT NULL DEFAULT 0,
  MODIFY `endDate` BIGINT NOT NULL DEFAULT 0;

ALTER TABLE `auto_announcements`
  MODIFY `id` INT UNSIGNED NOT NULL,
  MODIFY `initial` BIGINT UNSIGNED NOT NULL,
  MODIFY `delay` BIGINT UNSIGNED NOT NULL,
  MODIFY `cycle` INT UNSIGNED NOT NULL;
