ALTER TABLE `castle` ADD `newTax` TINYINT(2) UNSIGNED NOT NULL DEFAULT 0 AFTER `taxPercent`;
ALTER TABLE `castle` ADD `taxSetDate` BIGINT UNSIGNED NOT NULL DEFAULT 0 AFTER `newTax`;
ALTER TABLE `castle` MODIFY `name` VARCHAR(10) NOT NULL;
ALTER TABLE `castle` MODIFY `taxPercent` TINYINT(2) UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `castle` MODIFY `treasury` INT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `castle` MODIFY `siegeDate` BIGINT UNSIGNED NOT NULL DEFAULT 0;
ALTER TABLE `castle` MODIFY `regTimeEnd` BIGINT UNSIGNED NOT NULL DEFAULT 0;

ALTER TABLE `castle_doorupgrade` DROP `hp`, DROP `pDef`, DROP `mDef`;
ALTER TABLE `castle_doorupgrade` ADD `level` TINYINT(1) UNSIGNED NOT NULL;