ALTER TABLE `character_instance_time`
MODIFY `charId` INT UNSIGNED NOT NULL,
MODIFY `instanceId` SMALLINT UNSIGNED NOT NULL,
MODIFY `time` BIGINT UNSIGNED NOT NULL;

ALTER TABLE `castle_functions`
MODIFY `lvl` SMALLINT UNSIGNED NOT NULL;